# Generated by Django 6.0.1 on 2026-08-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0002_alter_enquirystatus_date_of_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquirydata",
            name="health_history_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
