# Generated by Django 6.0.1 on 2026-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0003_enquirydata_health_history_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquirydata",
            name="phone_number",
            field=models.BigIntegerField(),
        ),
    ]
