# Generated by Django 5.0.6 on 2025-08-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0018_alter_memberdata_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sub_disable',
            field=models.BooleanField(default=False),
        ),
    ]
